# Generated by Django 3.1.1 on 2020-10-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('rol', models.IntegerField(choices=[(1, 'Funcionario Gerente'), (2, 'Funcionario Jefe'), (3, 'Funcionario Subordinado'), (4, 'Diseñador de Procesos')])),
            ],
        ),
        migrations.CreateModel(
            name='UnidadInterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('plazo', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.IntegerField(choices=[(1, 'En Desarrollo'), (2, 'Completada'), (3, 'Atrasada')])),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='unidadInterna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidadinterna', verbose_name='Unidad Interna'),
        ),
    ]
